implement captcha service with implementation for reCAPTCHA
celements/celements-captcha pull request #1
Opened 2020-01-17 17:30 UTC by ebeutler

https://synjira.atlassian.net/browse/CELDEV-863

2020-01-23 18:00 UTC, msladek requested changes

2020-01-23 18:00 UTC, msladek commented on pom.xml
> +      <version>4.0</version>
don't use 4.x components in 3.x project

2020-01-24 08:38 UTC, ebeutler commented on pom.xml
> +      <version>4.0</version>
Good catch

2020-01-28 12:19 UTC, msladek approved these changes

2020-01-29 13:38 UTC, merged